version: "3.8"

services:
  mongodb:
    image :
      mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./DBZeug/mongo:/data/db
  backend:
    container_name: backend
    build: .
    ports:
    - "4444:4444"